### ISSUE TITLE
Implement threaded loading

### ISSUE THREAD

**Issue by edinosma** [edintomato2/Beret#2]
Right now, loading levels causes the entire editor to freeze up while objects are loaded and placed. I think it would be better to run all the importing on a separate thread, then show some sort of loading bar showing the state of what's being loaded.

**Comment by ghost** [comment]
Sorta completed with 9d5b0ae7c830385a710dbee83a0824e09c1fbc3f!
It still stops the program when loading some rather heavy levels, so I'll see if I can improve this.

**Comment by ghost** [comment]
Seems to be working with 1f2f6e2ed415f8f9f769a9ac209b8f00495571b5
